services:
  io_db:
    image: postgres:16
    container_name: io-db-mvc
    environment:
      POSTGRES_USER: io_user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: io_db
    ports:
      - "5433:5432"
    volumes:
      - io_pgdata:/var/lib/postgresql/data
    networks:
      - io_net

  io_pgadmin:
    image: dpage/pgadmin4:8
    container_name: io-pgadmin-mvc
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - io_db
    networks:
      - io_net

volumes:
  io_pgdata:

networks:
  io_net:
